spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql

management.endpoints.web.exposure.include: metrics, health, env, loggers

management.endpoint.health.show-details: always